### ISSUE TITLE
[Bug]: Bundling @babel/standalone by webpack emits warnings

### ISSUE THREAD

**Issue by joshuahhh** [babel/babel#14301]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

import '@babel/standalone';

### Configuration

N/A

### Current and expected behavior

**Current behavior:** When bundling a project with Webpack which includes code that imports '@babel/standalone', Webpack reports:

> WARNING in ./node_modules/@babel/standalone/babel.js 308:11-32
Critical dependency: the request of a dependency is an expression
 @ ./src/index.js 9:0-27
> 
> WARNING in ./node_modules/@babel/standalone/babel.js 346:11-24
Critical dependency: the request of a dependency is an expression
 @ ./src/index.js 9:0-27

I think this is due to `commonjsRequire`'s use of `require(path)`.

### Environment

Tested in a fresh `create-react-app` environment, as well as a more minimal Webpack environment.

### Possible solution

Given that @babel/standalone is intended for use in a browser environment, I wonder why it includes bare `require()` calls. Perhaps these parts could be excluded from this build?

### Additional context

Please let me know if there's anything else I can do to help. Thanks a bunch!

**Comment by JLHwung** [comment]
This is https://github.com/rollup/plugins/issues/1085.

**Comment by SxxPorsche** [comment]
@JLHwung hello, sorry to border you, is this bug has been fixed yet? I find the same question at version @babel/standalone@7.18.9

**Comment by liuxingbaoyu** [comment]
@SxxPorsche I simply searched in the file content and didn't find anything similar to `require(path)`, can you provide a reproducible repo?

**Comment by radhasatam** [comment]
Still facing this issue in `7.21.2`.

**Comment by liuxingbaoyu** [comment]
@radhasatam Can you provide a reproducible repo?

**Comment by Mity1299** [comment]
Still facing this issue in 7.21.4.
See: https://github.com/Mity1299/babel-standalone-webpack-bug
run `npm run build` will see the error: 
Critical dependency: the request of a dependency is an expression

**Comment by liuxingbaoyu** [comment]
Thanks, I can reproduce the problem.
Opened an issue https://github.com/rollup/plugins/issues/1472.

**Comment by tomitrescak** [comment]
That issue https://github.com/rollup/plugins/issues/1472 was closed due to inactivity ;( Is there another way out?

**Comment by nicolo-ribaudo** [comment]
It would be awesome if someone could work on a rollup PR to fix that issue :)

**Comment by liuxingbaoyu** [comment]
I'll try to do it in a few days. :) (previously I wasn't sure if this should open a rollup PR)

**Comment by mliudev** [comment]
In 2025 and still an issue. We're using this in our frontend with NextJS to transpile JSX on the fly.

**Comment by james-lawrence** [comment]
@mliudev think you're going to have report up stream to rollup. the issue was closed due to 'inactivity' there.
