### ISSUE TITLE
Error exporting default class that extends a base class

### ISSUE THREAD

**Issue by nightwolfz** [babel/babel#2694]
Looks like everytime I combine the keywords **export default** and **extends**, babel throws.

**Example 1 (exporting default named with extension)**

```javascript
import React from 'react';

export default class TestElement extends React.Component {
    constructor(){
        super();
    }
    render(){
        return <p>Test</p>
    }
}
```

**Stacktrace:**
```
/project/node_modules\babel-core\lib\transformation\file\index.js:519
      throw err;
      ^

SyntaxError: /project/test.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/project/node_modules\babel-core\lib\transformation\file\index.js:408:15)
    at NodePath.buildCodeFrameError (/project/node_modules\babel-traverse\lib\path\index.js:135:26)
    at [object Object].ThisExpression (/project/node_modules\babel-plugin-transform-es2015-classes\lib\vanilla.js:73:20)
    at NodePath._call (/project/node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (/project/node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (/project/node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (/project/node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (/project/node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (/project/node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (/project/node_modules\babel-traverse\lib\index.js:139:17)
```

**Example 2 (exporting default anonymous with extension)**

```javascript
import React from 'react';

export default class extends React.Component {
    constructor(){
        super();
    }
    render(){
        return <p>Test</p>
    }
}
```

**Stacktrace:**
```
/project/node_modules\babel-core\lib\transformation\file\index.js:519
      throw err;
      ^

TypeError: /project/test.js: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got null
    at Object.validate (/project/node_modules\babel-types\lib\definitions\index.js:97:13)
    at validate (/project/node_modules\babel-types\lib\index.js:267:9)
    at Object.builder (/project/node_modules\babel-types\lib\index.js:243:7)
    at PluginPass.ClassDeclaration (/project/node_modules\babel-plugin-transform-es2015-classes\lib\index.js:33:58)
    at newFn (/project/node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (/project/node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (/project/node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (/project/node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (/project/node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (/project/node_modules\babel-traverse\lib\context.js:111:19)
```

**Example 3 (exporting default anonymous without extension)**

```javascript
import React from 'react';

export default class {
    render(){
        return <p>Test</p>
    }
}
```

**Stacktrace:**
```
/project/node_modules\babel-core\lib\transformation\file\index.js:519
      throw err;
      ^

TypeError: /project/test.js: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got null
    at Object.validate (/project/node_modules\babel-types\lib\definitions\index.js:97:13)
    at validate (/project/node_modules\babel-types\lib\index.js:267:9)
    at Object.builder (/project/node_modules\babel-types\lib\index.js:243:7)
    at PluginPass.ClassDeclaration (/project/node_modules\babel-plugin-transform-es2015-classes\lib\index.js:33:58)
    at newFn (/project/node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (/project/node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (/project/node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (/project/node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (/project/node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (/project/node_modules\babel-traverse\lib\context.js:111:19)
```

**The following works**
```javascript
export default class {
    constructor(){
    }
    render(){
        return <p>Test</p>
    }
}
```

```javascript
export default class Test {
    constructor(){

    }
    render(){
        return <p>Test</p>
    }
}
```

**Node: 5.0.0**

**.babelrc**
```json
{
  "highlightCode": true,
  "plugins": [
    "transform-react-jsx",
    "transform-es2015-arrow-functions",
    "transform-es2015-block-scoped-functions",
    "transform-es2015-classes",
    "transform-es2015-block-scoping",
    "transform-es2015-modules-commonjs"
  ]
}
```

**Comment by rafalszemraj** [comment]
Same with me. Current workaround:
**component:**
```javascript
import React from 'react';
module.exports = class Test extends React.Component {
    constructor(){
        super();
    }
    render(){
        return <p>Test</p>
    }
}
```

**.babelrc:**
```json
{
  "presets": [
      "es2015",
      "react"
   ]
}
```

**Comment by hzoo** [comment]
Hopefully this is the same issue since I'm getting a similar error with https://github.com/hzoo/cst/blob/babel-6/src/elements/types/Program.js#L11-L17 (below)

```js
constructor(childNodes: Array<any>) {
        super('Program', childNodes);

        this._isProgram = true;
        this._searchIndex = new ElementSearchIndex();
        this._searchIndex.addElements(childNodes);
    }
```

```bash
> mocha test/utils.js test/lib test/integrated src --recursive --compilers js:babel-core/register

--------------
_isProgram
undefined
this.hasBareSuper true
--------------
_searchIndex
undefined
this.hasBareSuper true
--------------
_searchIndex
undefined
this.hasBareSuper true
--------------
undefined
{ type: 'Identifier', name: '_possibleConstructorReturn' }
this.hasBareSuper undefined
/Users/hzhu/dev/cst/node_modules/babel-core/lib/transformation/file/index.js:519
      throw err;
            ^
SyntaxError: /Users/hzhu/dev/cst/src/elements/types/Program.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/Users/hzhu/dev/cst/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (/Users/hzhu/dev/cst/node_modules/babel-traverse/lib/path/index.js:135:26)
    at [object Object].ThisExpression (/Users/hzhu/dev/cst/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:78:20)
    at NodePath._call (/Users/hzhu/dev/cst/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/hzhu/dev/cst/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/hzhu/dev/cst/node_modules/babel-traverse/lib/path/context.js:102:12)
```

Added
```
console.log('--------------');
    console.log(path.parent.property && path.parent.property.name);
    console.log(path.parent.callee);
    console.log('this.hasBareSuper ' + this.hasBareSuper);
```

https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-classes/src/vanilla.js#L46-L52

So there are 3 `ThisExpression` but it looks like it is visiting an extra `ThisExpression` 

`{ type: 'Identifier', name: '_possibleConstructorReturn' }` where `this.hasBareSuper` is `undefined`

**Comment by electerious** [comment]
Having the exact same issues as @nightwolfz. Seems to be an problem of `babel-plugin-transform-es2015-classes` and maybe related to #2700, #2663, …

**Comment by sunjay** [comment]
Also having this issue. Removing `export default` and moving it to the bottom works around the issue, but it would be nice to get this support back.

**Comment by austinlyons** [comment]
Same as sunjay

**Comment by leebenson** [comment]
+1. Having to refactor 100+ React components to drop `export default class` syntax to workaround. Not a huge deal, but this cryptic error will cause a lot of confusion.

**Comment by tofagerl** [comment]
Is this considered a bug, then? Or some sort of weird wontfix...?

**Comment by electerious** [comment]
Issue #2700 has been fixed, but `extends` still makes trouble (Babel v6.0.20). I get the following:

```
Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got null while parsing file: […]Main.js
```

Main.js:
```js
import Menu from './Menu'
import Plugins from './Plugins'
import React from 'react'

export default class extends React.Component {

	render() {

		return (
			<div>
				<Menu />
				<Plugins plugins={ this.props.plugins } />
			</div>
		)

	}

}
```

**Comment by hzoo** [comment]
For @electerious' issue

```bash
TypeError: index.js: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got null
    at Object.validate (/Users/hzhu/dev/babel/packages/babel-types/lib/definitions/index.js:99:13)
    at validate (/Users/hzhu/dev/babel/packages/babel-types/lib/index.js:295:9)
    at Object.builder (/Users/hzhu/dev/babel/packages/babel-types/lib/index.js:248:7)
    at PluginPass.ClassDeclaration (/Users/hzhu/dev/test-jscs/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:36:58)
```

at `t.variableDeclarator(node.id, t.toExpression(node));` I guess node.id is null since it is `export default class extends`

https://github.com/babel/babel/blob/4d1145f8721a05cee79201d52583559d4f5939f4/packages/babel-plugin-transform-es2015-classes/src/index.js#L17

so we just have to replace that with a default name?

**Comment by bugeats** [comment]
Confirming @sunjay `export default class App extends Component` --> `class App extends Component` prevents the cryptic error.

**Comment by tofagerl** [comment]
I don't know if this is solved in 6.1.2, since I'm now running into #2809 instead - yay - but at least there is some movement...

**Comment by rusel1989** [comment]
I think the problem still remains even in 6.1.2 but at least @sunjay 's solution works...

**Comment by sebmck** [comment]
This should be fixed in `master`.

**Comment by pmros** [comment]
Using babel 6.1.4, the problem still remains.

**Comment by animecyc** [comment]
I'm also seeing this issue in 6.1.4 still.

**Comment by hzoo** [comment]
Do yall have code snippets/babelrc for this?

**Comment by williamboman** [comment]
Works fine for me on 6.1.4, https://github.com/williamboman/babel-errors/tree/export-default-subclass.

**Comment by animecyc** [comment]
**Node:** v0.10.40
**Babel:** 6.1.4

> I'm running this via nodemon/babel-node: `nodemon --exec babel-node -- ./src/index.js`

---
**Error:** `SyntaxError: [[REDACTED]]/PortalController.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)`

**.bablerc**
```json
{
  "presets": ["es2015"]
}
```

**FooController.js**
```javascript
import Controller from '../../core/controller';

export default class FooController extends Controller {
  constructor () {
    super();
  }
}
```

**Controller.js**
```javascript
export default class Controller {}
```

**Comment by williamboman** [comment]
> SyntaxError: [[REDACTED]]/FooController.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)

See https://github.com/babel/babel/issues/2775.

**Comment by animecyc** [comment]
@williamboman I've just added a constructor to both classes and get the same error:

---

**FooController.js**
```javascript
import Controller from '../../core/controller';

export default class FooController extends Controller {
  constructor () {
    super();
  }
}
```

**Controller.js**
```javascript
export default class Controller {
  constructor () {
    //
  }
}
```

**Comment by animecyc** [comment]
@williamboman To note, I just tested the code you provided and while it works when transpiling via the `babel` command, running it in `babel-node` fails with the same error.

**Comment by BowlingX** [comment]
Same problem here, weird thing: If I link a module with `npm link myDependency` it works...

**Comment by XescuGC** [comment]
I have the same issue, the current workaround for me is to not use the `default`.

With error:
```
// Base.js
export default class Base {};

// Person.js
import Base from './Base';
export default Person extends Base {};

// Client
import Person from './Person';
class Client extends Person {};
```

Workaround:

```
// Base.js
export default class Base {};

// Person.js
import Base from './Base';
export class Person extends Base {};

// Client
import { Person } from './Person';
class Client extends Person {};
```

I'm using: 
  * `babel` version `6.1.4 (babel-core 6.1.4)`
  * `babel-node` version `6.1.4`
  * `babel-present-es2015` version `6.1.4` with a `.babelrc`: ` { "presets": ["es2015"] }`
  * Tested with `node` versions: `5.0.0`, `4.1.0` and `0.12.7`

**Comment by williamboman** [comment]
@XescuGC I can't reproduce what you've pasted, exact same setup (see https://github.com/williamboman/babel-errors/tree/export-default-subclass1).

**Comment by sebmck** [comment]
Just fixed #3028. Might have been the cause. Please retest on 6.1.20.

**Comment by pmros** [comment]
Using babel 6.1.20, the problem still remains.

**Comment by williamboman** [comment]
It only fails with `babel-node`.

**Comment by aputinski** [comment]
Same here, I'm on 6.1.20 (w/ fresh `npm install`) and still getting this error when using `babel-node`

**Comment by resurge** [comment]
I'm using `babel-core` and `babel-preset-es2015` and having the same issue.  
I'm calling `require('babel-core/register');` in the start of my code.

Not using `babel-node` afaik. Unless it's used internally somewhere?  
Don't know much about the working of babel.

**Comment by sebmck** [comment]
Run babel-doctor: https://babeljs.io/blog/2015/11/03/babel-doctor/ Make
sure you're on all the latest.

On Fri, Nov 13, 2015 at 8:52 AM, Jeroen Pelgrims <notifications@github.com>
wrote:

> I'm using babel-core and babel-preset-es2015 and having the same issue.
>
> I'm calling require('babel-core/register'); in the start of my code.
>
> Not using babel-node afaik. Unless it's used internally somewhere?
>
> Don't know much about the working of babel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2694#issuecomment-156485691>.
>



-- 
Sebastian McKenzie

**Comment by aputinski** [comment]
@sebmck Just ran `babel-doctor` and got "✔ All babel packages appear to be up to date", but still getting 

```
TypeError: object is not a function
    at exports.default (/project/node_modules/babel-runtime/helpers/typeof.js:14:174)
```

**Comment by resurge** [comment]
@sebmck After running some of the suggested commands babel-doctor says everything is okay now. But am still having the same error.
Not sure if it has been mentioned before here but I'm only having this problem with a class that extends from an other class.
So `export default class Foo {}` works but `export default class Bar extends Foo {}` doesn't.

**Comment by resurge** [comment]
@sebmck I created a minimal example describing the issue here: https://github.com/resurge/babel-export-default-error

**Comment by sebmck** [comment]
I can repro, thanks @resurge!

**Comment by sebmck** [comment]
Just pushed 6.1.21 which should contain a fix. Can the people effected please confirm that it works and fixes your specific issue.

**Comment by williamboman** [comment]
Seems to be OK now, although `babel-node` is not functional on `node<4` (https://travis-ci.org/williamboman/babel-errors/builds/91056844).

**Comment by resurge** [comment]
Works smoothly for that example repo, but I seem to be getting an error in my real project.

`var BaseTest = class BaseTest {
               ^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at loader (/home/jeroenp/Altibox/altibox-web/trunk/static/webapps/altibox/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jeroenp/Altibox/altibox-web/trunk/static/webapps/altibox/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jeroenp/Altibox/altibox-web/trunk/static/webapps/altibox/apps/user/selfcare/example-test/ExampleTest.js:12:18)
    at Module._compile (module.js:456:26)
    at loader (/home/jeroenp/Altibox/altibox-web/trunk/static/webapps/altibox/node_modules/babel-register/lib/node.js:128:5)`

Seems to be something is going wrong in transpiling? The class keyword is coming through in the resulting ES5 code.
I'm getting this with either setting export default on the base or deriving class. (removing default makes everything work normally, so this seems to be related)

**Comment by nishant-jichkar** [comment]
i am getting somewhat similar : 
(function (exports, require, module, __filename, __dirname) { export default class  stateCleintHelper {
                                                                                                      ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
