### ISSUE TITLE
Arrow function in React.Component class fails

### ISSUE THREAD

**Issue by calitek** [babel/babel#3045]
babel.core 6.1.20

The error message.

'this' is not allowed before super()

Here is the code that breaks.
```
export default class AppCtrl extends React.Component {
  constructor() { super(); this.state = {world: ''}; }
  componentDidMount() { this.sayHello(); }
  sayHello = () => { this.setState({world: 'Hello World'}); }
  render() {
    return (
      <div id='AppCtrlSty' style={AppCtrlSty}>
        React 1.4 Basic
        <br/><br/>
        {this.state.world}
      </div>
    );
  }
}
```
Here is the code that works.
```
export default class AppCtrl extends React.Component {
  constructor() { super(); this.state = {world: ''}; }
  componentDidMount() { this.sayHello(); }
  sayHello() { this.setState({world: 'Hello World'}); }
  render() {
    return (
      <div id='AppCtrlSty' style={AppCtrlSty}>
        React 1.4 Basic
        <br/><br/>
        {this.state.world}
      </div>
    );
  }
}
```
The gulp code.
```
gulp.task('appjs', function(){
  browserify({ debug: true })
  .transform(babel, {
    presets:["stage-0", "es2015", "react"],
    plugins: ["syntax-class-properties", "transform-class-properties"]
  })
  .require(source.appjs, { entry: true })
  .bundle()
  .pipe(vsource('app.min.js'))
  .pipe(gulp.dest('./ui-dist'));
});
```

**Comment by joshacheson** [comment]
I am having the same issue more or less, with the arrow function declared inside the components `render` method.

**Comment by julienvincent** [comment]
This was solved in -v `6.1.20` - [#3028](https://github.com/babel/babel/issues/3028). Make sure you are using a clean node_modules.

**Comment by calitek** [comment]
You should note that I included the build at the top of the note. I did start with an empty node_modules. Tested again just now and same error.

**Comment by calitek** [comment]
In looking at #3028 I wondered if the this in the arrow function mattered. It does, so it is a combination of the arrow function and "this" that is creating the error.

**Comment by julienvincent** [comment]
I am unable to reproduce the error you are seeing. Maybe create a repro repo and a collaborator can take a look.

**Comment by calitek** [comment]
I removed the global babel and cleared the node_modules again and still get the error. Here is the repo https://github.com/calitek/BasicStarter. It reproduced the error on my system (osx latest).

**Comment by julienvincent** [comment]
Oh I see you are using babelify. I don't think the fix has been ported to that yet - the 3028 bug still exists in babelify

**Comment by calitek** [comment]
Thanks Julien, sorry about the renaming in the gulp example. I wasn't thinking. So what should I look for to know when babelify is ready?

**Comment by julienvincent** [comment]
I'm assuming the next version would contain the latest babel-core so just watch out for new version releases.

**Comment by calitek** [comment]
The version of babelify I used does contain the latest core. Having the same problem with webpack. Go figure.

**Comment by julienvincent** [comment]
Well I have no idea then. @sebmck the [#3028](https://github.com/babel/babel/issues/3028) bug you solved still exists in browserify?

**Comment by thejameskyle** [comment]
What? Transformation issues don't need to be fixed in both `babel-core` and `babelify`. `babelify` depends on `babel-core`...

And the version in the babel-core dependency will cover all the latest releases. https://github.com/babel/babelify/blob/1b381da80249040588d1e6919a2190b1997bc09d/package.json#L16
