### ISSUE TITLE
transform-runtime plugin option ignored for "polyfill":false

### ISSUE THREAD

**Issue by sudo-suhas** [babel/babel#5382]
`transform-runtime` plugin usage option for disabling polyfills is ignored when used to transpile code with async functions.
### Input Code
I am able to reproduce the bug using the vue [webpack template](https://github.com/vuejs-templates/webpack) starter pack.

To create a fresh project:
```
$ npm install -g vue-cli
$ vue init webpack vue-test

  This will install Vue 2.x version of the template.

  For Vue 1.x use: vue init webpack#1.0 vue-test

? Project name vue-test
? Project description Playground for Vue!
? Author Suhas Karanth <sudo.suhas@gmail.com>
? Vue build runtime
? Install vue-router? Yes
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Mocha? No
? Setup e2e tests with Nightwatch? No

   vue-cli · Generated "vue-test".

   To get started:
   
     cd vue-test
     npm install
     npm run dev
   
   Documentation can be found at https://vuejs-templates.github.io/webpack

$ cd vue-test/
$ npm install
```
Modify `.babelrc` to have `["transform-runtime", { "polyfill": false }]`. 

Add the following to `src/main.js`:
```js
async function test() {
    await Promise.resolve(true);
}
```

### Babel Configuration (.babelrc, cli command)

```js
// .babelrc
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": [["transform-runtime", { "polyfill": false }]],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}

// cli command
npm run build --report
```

### Expected Behavior
Since polyfill option is disabled, core-js modules should not be exported.

### Current Behavior
The polyfills are added despite the `.babelrc` config
![image](https://cloud.githubusercontent.com/assets/22251956/23338239/3cd8c52e-fc2b-11e6-8ab4-3e5bd9732309.png)

### Context
I am tying to export my choice of polyfill of promise library but the build ends up exporting both the polyfill library as well as the core-js promise version. 

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.1
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | ubuntu 16.04

**Comment by hzoo** [comment]
this is because the helpers pull in core-js as well. should be fixed in https://github.com/babel/babel/pull/5442 with the useBuiltIns option in 7.0 so that the helpers don't also import core-js, https://github.com/babel/babel/pull/5481 (docs prs)

**Comment by sudo-suhas** [comment]
Great :smile: If you don't mind, could you also tell me by when 7.0 might be released?

**Comment by hzoo** [comment]
No schedule, we will be releasing alpha/rc versions over time though, probably another one with that PR this week.

**Comment by sudo-suhas** [comment]
@hzoo I think we need to reopen this issue. I tried the steps with the latest beta for babel packages but the issue still persists.

**`.babelrc`**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "useBuiltIns": false, // I also tried it with `"usage"`
      "debug": true
    }],
    "@babel/preset-stage-2"
  ],
  "plugins": [["@babel/plugin-transform-runtime", { "polyfill": false }]],
  "env": {
    "test": {
      "presets": ["@babel/preset-env", "@babel/preset-stage-2"],
      "plugins": ["@babel/plugin-transform-modules-commonjs", "dynamic-import-node"]
    }
  }
}

```

**`package.json` snippet**
```js
{
  // ...
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.32",
    "@babel/plugin-transform-modules-commonjs": "^v7.0.0-beta.32",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.32",
    "@babel/preset-env": "^v7.0.0-beta.32",
    "@babel/preset-stage-2": "^7.0.0-beta.32",
    "@babel/register": "^7.0.0-beta.32",
    "@babel/runtime": "^7.0.0-beta.32",
    "babel-loader": "^8.0.0-beta.0",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    // ...
  }
}
```

**Build output:**
```
λ npm run build --report

> vue-webpack-dev@1.0.0 build E:\Projects\experiments\vue-webpack-dev
> node build/build.js

/ building for production...@babel/preset-env: `DEBUG` option

Using targets:
{
  "android": "4.4.3",
  "chrome": "60",
  "edge": "15",
  "firefox": "56",
  "ie": "10",
  "ios": "10.3",
  "safari": "10.1"
}

Using modules transform: false

Using plugins:
  check-constants { "android":"4.4.3", "ie":"10" }
  transform-arrow-functions { "android":"4.4.3", "ie":"10" }
  transform-block-scoped-functions { "android":"4.4.3", "ie":"10" }
  transform-block-scoping { "android":"4.4.3", "ie":"10" }
  transform-classes { "android":"4.4.3", "ie":"10" }
  transform-computed-properties { "android":"4.4.3", "ie":"10" }
  transform-destructuring { "android":"4.4.3", "edge":"15", "ie":"10" }
  transform-duplicate-keys { "android":"4.4.3", "ie":"10" }
  transform-for-of { "android":"4.4.3", "ie":"10" }
  transform-function-name { "android":"4.4.3", "edge":"15", "ie":"10" }
  transform-literals { "android":"4.4.3", "ie":"10" }
  transform-object-super { "android":"4.4.3", "ie":"10" }
  transform-parameters { "android":"4.4.3", "ie":"10" }
  transform-shorthand-properties { "android":"4.4.3", "ie":"10" }
  transform-spread { "android":"4.4.3", "ie":"10" }
  transform-sticky-regex { "android":"4.4.3", "ie":"10" }
  transform-template-literals { "android":"4.4.3", "ie":"10" }
  transform-typeof-symbol { "android":"4.4.3", "ie":"10" }
  transform-unicode-regex { "android":"4.4.3", "ie":"10" }
  transform-new-target { "android":"4.4.3", "ie":"10" }
  transform-regenerator { "android":"4.4.3", "ie":"10" }
  transform-exponentiation-operator { "android":"4.4.3", "ie":"10" }
  transform-async-to-generator { "android":"4.4.3", "ie":"10" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
Hash: 42945cf67871b2638c12
Version: webpack 3.8.1
Time: 8183ms
                                                  Asset       Size  Chunks             Chunk Names
               static/js/vendor.f2c85cd40521aad61df7.js     119 kB       0  [emitted]  vendor
                  static/js/app.75db56a85be54c0ad27c.js    11.8 kB       1  [emitted]  app
             static/js/manifest.e332e65c5c9f65ce1973.js    1.51 kB       2  [emitted]  manifest
    static/css/app.d90fac408992be41cff8ba63f004fedd.css  432 bytes       1  [emitted]  app
static/css/app.d90fac408992be41cff8ba63f004fedd.css.map  828 bytes          [emitted]
           static/js/vendor.f2c85cd40521aad61df7.js.map     971 kB       0  [emitted]  vendor
              static/js/app.75db56a85be54c0ad27c.js.map    39.3 kB       1  [emitted]  app
         static/js/manifest.e332e65c5c9f65ce1973.js.map    14.4 kB       2  [emitted]  manifest
                                             index.html  517 bytes          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
```
