### ISSUE TITLE
let [a, ...[b, c, ...d]] = "hello"; console.log(a, b, c, d) Unexpected token (1:11)

### ISSUE THREAD

**Issue by graingert** [babel/babel#6340]
Choose one: is this a bug report or feature request? bug-ish

### Input Code
```sh
node -v
8.6.0
node -e 'let [a, ...[b, c, ...d]] = "hello"; console.log(a, b, c, d)'
h e l [ 'l', 'o' ]
```

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBA2ghgNBAdMqAjBBjBzEBMC6-EAvBAEQAWIwwA9mQNwQa0B2AzraInQOYAU8COmYJcASgZA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=&version=6.26.0

### Babel Configuration (.babelrc, package.json, cli command)
see repl URL

### Expected Behavior
Not really sure

### Current Behavior
SyntaxError

### Possible Solution
Is this node that's wrong of Babel?

If it is node that's wrong, It'd still like to be able to parse those invalid statements to I can convert them into valid ones.

### Context
I can't webpack stuff that uses this construct.

### Your Environment
See REPL URL

**Comment by hzoo** [comment]
This is fixed on master, so you can try 7.x (/repl/build/master)

https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBA2ghgNBAdMqAjBBjBzEBMC6-EAvBAEQAWIwwA9mQNwQa0B2AzraInQOYAU8COmYJcASgZA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.0.0-beta.2

**Comment by graingert** [comment]
Aww dang

**Comment by graingert** [comment]
What's the ETA on 7.x final?

**Comment by hzoo** [comment]
no guaranteed eta, we're working on it - I would try the beta

**Comment by graingert** [comment]
@hzoo hmm, I tried using "babel-eslint" but it still failed for me: https://travis-ci.org/mysticatea/eslint-plugin/jobs/281424580

https://github.com/mysticatea/eslint-plugin/pull/16

**Comment by graingert** [comment]
@hzoo hmm, I tried using "babel-eslint" but it still failed for me: https://travis-ci.org/mysticatea/eslint-plugin/jobs/281424580

https://github.com/mysticatea/eslint-plugin/pull/16

**Comment by graingert** [comment]
Oh woops, I got confused, those tests are failing property spread
