### ISSUE TITLE
object-rest not behaving as expected with computed properties

### ISSUE THREAD

**Issue by lslv1243** [babel/babel#6341]
Choose one: is this a bug report or feature request?
bug

### Input Code

```js
const a = { 1: 0, 2: 1, 3: 2 }
const i = 1
const { [i]: val, ...rest } = a
```

### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

### Expected Behavior

rest should be 
```javascript
{
  "2": 1,
  "3": 2,
}
```

### Current Behavior

rest is 
```javascript
{
  "1": 0,
  "2": 1,
  "3": 2,
}
```

### Possible Solution

indexOf compares with 3 equals and the object key is represented as string
https://github.com/babel/babel/blob/88b7983e4f1b4d472f37c057afce0e86da7feb0b/packages/babel-helpers/src/helpers.js#L469

### Context

running react-native application

### Your Environment

using react native with expo
```json
{
  "expo": {
    "sdkVersion": "21.0.0"
  }
}
```
dont know about configuration

**Comment by Andarist** [comment]
Thanks for the report @lslv1243 . It is indeed a bug, let me look into fixing it.

**Comment by Andarist** [comment]
This already got fixed by https://github.com/babel/babel/pull/5757 and the fix is available in v7. 

For some reason when having preset-es2015 + stage-3 active in the repl it creates buggy output. stage-3 alone is working as expected.

**Comment by Andarist** [comment]
Ok, got down to it - in v7 there is still a conflict when using both:
- babel-plugin-transform-es2015-destructuring
- babel-plugin-transform-object-rest-spread

**Actual output**
```
var a = {
  1: 0,
  2: 1,
  3: 2
};
var i = 1;
var val = a[i],
    rest = babelHelpers.objectWithoutProperties(a, [i]);
```

**Expected output**
```
var a = {
  1: 0,
  2: 1,
  3: 2
};
var i = 1;
var val = a[i],
    rest = babelHelpers.objectWithoutProperties(a, [i].map(babelHelpers.toPropertyKey));
```

**Comment by jridgewell** [comment]
There's all kinds of bugs with using destructuring and object-rest-spread together. It's on my list of todos.

**Comment by cgood92** [comment]
Having the same problem.

```
const obj = {
  0: true,
  1: 'hi',
  2: true,
}

const { [1]: number1, ...rest1 } = obj
const { ['1']: number2, ...rest2 } = obj


console.log(number1, rest1)
// => "hi", { 0: true, 1: 'hi', 2: true }

console.log(number2, rest2)
// => "hi", { 0: true, 2: true }
```

**Comment by PJCHENder** [comment]
@Andarist 

It seems that this bug has not been fixed yet in Babel v7.
I use Babel REPL to reproduce the issue.
https://goo.gl/7ed5Tq

The compiled version still not using String as key:

```javascript
let obj = { 1: 1, 2: 2, 3: 3, 4: 4 };
const { 1: value } = obj,
  newState = _objectWithoutProperties(obj, [1]);
```

To get the expected result, it should be:

```javascript
const { 1: value } = obj,
  newState = _objectWithoutProperties(obj, ['1']);
```

Therefore, the rest property still won't work correctly when the object key is Number.

**Comment by Andarist** [comment]
There is indeed some problem, at least with the REPL. It's weird because REPL shows different outputs than what we have as expected results in our tests (tests are handling this correctly - by introducing a `toPropertyKey` helper)

Could you test this in a sample project?

**Comment by nicolo-ribaudo** [comment]
The repl still uses Babel 6 by default. You can use https://babeljs.io/repl/build/master to check the current behavior.

**Comment by Andarist** [comment]
And this newer REPL also shows different results than tests on master 🤔 I have also previously tested this on the older REPL but I have used it with babel@7 by changing the query params (although couldnt use latest for some reason there, so I was stuck on rc4 or some similar version)

**Comment by PJCHENder** [comment]
Thanks for testing, @Andarist. 
I found this issue with the environment settings:  `["@babel/core": "^7.0.1", "@babel/preset-env"]` which was based on a React project.

**Comment by rareyesdev** [comment]
I'm also experiencing this with `7.7.5`.

[REPL](https://babeljs.io/repl#?browsers=safari%2010.1&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBADgJxHAcgQwLYFMYF4YDkiy62AamgDYCuWBA3AFCMBm1YwUAluDCyCAAUAbxgBtYqkxYAugC4YotABoYAI1UA6bQizQYAX0MBKRYxgxdUagjCW9UJgaA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.7.5&externalPlugins=)

Original:
```javascript
const propName = 'propNameValue';

function foo({ [propName]: { a, b, ...rest } }) {
  return rest;
}
```

Result:
```javascript
var propName = 'propNameValue';

function foo(_ref) {
  var {
    [propName]: {
      a,
      b
    }
  } = _ref,
      rest = _objectWithoutProperties(_ref.propName, ["a", "b"]);

  return rest;
}
```

The problem is that is trying to read `_ref.propName` instead of `_ref[propName]`
