### ISSUE TITLE
proposal-object-rest-spread doesn't transform the rest/spread syntax in some cases

### ISSUE THREAD

**Issue by gaearon** [babel/babel#7215]
This looks superficially similar to https://github.com/babel/babel/issues/7099 but that one is supposedly [resolved in Babel 7](https://github.com/babel/babel/issues/7099#issuecomment-357065187) but my bug isn’t. Therefore I’m filing a new one.

Here is a complete repro:

```sh
npm i --save @babel/core@7.0.0-beta.37 @babel/plugin-proposal-object-rest-spread@7.0.0-beta.37
```

Then run in Node shell:

```js
console.log(
  require('@babel/core').transform(
`
const { ...rest1 } = {};
const [{ ...rest2 }] = [{}];
`,
    {
      plugins: ['@babel/plugin-proposal-object-rest-spread']
    }
  ).code
)
```

Notice how I have two different rest destructurings, but the second one is *also* inside an array destructuring.

Output:

```js
function _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }

const rest1 = _objectWithoutProperties({}, []);

const [{ ...rest2
}] = [{}];
```

Notice how `...rest1` got transformed but `...rest2` is left intact.

I expect that `...rest2` is also transformed.

---

Original issue where this got reported: https://github.com/facebookincubator/create-react-app/issues/3694

**Comment by hzoo** [comment]
Weird, can repro with the [repl](https://babeljs.io/repl/build/master#?babili=false&browsers=ie%209&build=&builtIns=true&code_lz=MYewdgzgLgBA3jAdMgTgU2gRhgXxgXnhwG4AoUSWAbQWUXWgCZcBdAmGnFsoA&debug=true&circleciRepo=&evaluate=false&fileSize=true&lineWrap=true&presets=stage-3&prettier=false&targets=&version=7.0.0-beta.37)

**Comment by gaearon** [comment]
I think this is present in 6.x too by the wat.

**Comment by gaearon** [comment]
Do you think there's any possible workaround we could ship until this is fixed? My impression is since the plugin doesn't *see* the node, there's nothing we could do on our side. But maybe I'm wrong?

**Comment by hzoo** [comment]
Well it looks like on 6.x it's a syntax error so it wasn't parsable `const [{ awesome, ...rest}] = arrayOfObjects` while in 7.x we can parse it but the transform wasn't written maybe? I think that is fine given it prevents users from using it and we can fix it in 7.x?

**Comment by gaearon** [comment]
I see, thanks for explaining. This makes sense.

**Comment by hzoo** [comment]
some more history: I wrote the original one because we actually didn't even have it implemented - it was done through "destructuring" which wasn't a problem but after I added preset-env, we didn't have an independent transform for it so I made a simple one that obviously had a lot of bugs/edge cases. @jridgewell made https://github.com/babel/babel/pull/5981 but seems like we closed it

**Comment by gaearon** [comment]
Does this mean that adding `destructuring` transform would fix this?

**Comment by hzoo** [comment]
Not in this case because ^ I mentioned it would syntax error in 6.x so this type of code was never considered - based on that probably not unless it just happens to work?

**Comment by gaearon** [comment]
It seems like this works?

http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBA2gbwHQoE4FNoF8C6MC88CuA3EA&debug=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015%2Cstage-1&prettier=false&targets=Node-6.12&version=6.26.0

**Comment by hzoo** [comment]
oh ok 😄 🙌?

**Comment by gaearon** [comment]
If the fix is not obvious, could we treat `destructuring` as a prerequisite for `object-rest-spread`, and include both in `env` even if technically only `object-rest-spread` is needed?

**Comment by gaearon** [comment]
Never mind, I forgot `env` is unaware of `object-rest-spread` in the first place

**Comment by Andarist** [comment]
Actually env is aware of this transforms, thanks to [shippedProposals flag](https://github.com/babel/babel/tree/2d05487293278286e352d7acc0761751025b4b1a/packages/babel-preset-env#shippedproposals), but anyway the correct fix is to fix this in the transform itself - hopefully it will get fixed soon enough.

**Comment by maaz93** [comment]
I'd like to take this up if that's ok! I'm aware of the area where the fix needs to be done (the `proposal-object-rest-spread` plugin). Will ping back if I need any help. 😄

**Comment by Andarist** [comment]
Would be great! You can compare actual implementation with previously created #5981 to see what cases did the other one handled and if maybe this code could get reused for `object-rest-spread` cleanup. Join our Slack if you have any questions :)

**Comment by existentialism** [comment]
@maaz93 I know @jridgewell fixed a number of additional cases in object-rest-spread inside https://github.com/babel/babel/pull/5981 that never landed... might be worth taking a look in there as a ref.

**Comment by maaz93** [comment]
Sure! Any reason why that PR was not merged? There are no details within that.

**Comment by existentialism** [comment]
@maaz93 it just got really outdated from merging some other PRs and IIRC just hadn't been updated

**Comment by vinerz** [comment]
Having the same issue here. The plugin does not throw errors and the parser can deal with it, but the transform silently fails and does not touch on the spread operator, giving the same output.

**Comment by evilebottnawi** [comment]
Looks problem solved in `babel@7`. Can't reproduce using
```js
console.log(
  require('@babel/core').transform(
    `
const { ...rest1 } = {};
const [{ ...rest2 }] = [{}];
`,
    {
      plugins: ['@babel/plugin-proposal-object-rest-spread']
    }
  ).code
)
```

**Comment by DinakaranS** [comment]
Can this be fixed ? I am getting the same error in ie 11

**Comment by nicolo-ribaudo** [comment]
Babel version? Can you share a reproducible example?

**Comment by ThiefMaster** [comment]
This is still an issue (#10257) - and I think nowadays where more and more people drop support for old browsers (IE11) this becomes a bigger problem as the bug does not occur if you include IE11 in the preset-env targets (`transform-destructuring` replaces the whole destructuring expression when targetting IE11)

**Comment by kailight** [comment]
I am having problem with spread syntax in Edge, using following babelrc

`presets: [
    [
      '@babel/preset-env', {
        modules: 'commonjs',
        include : [
          "@babel/plugin-proposal-object-rest-spread"
        ]
      }
    ]
  ],
  plugins: [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread"
  ]`

Is my problem related to this thread?
