### ISSUE TITLE
babel/babel-node won't transpile node_modules

### ISSUE THREAD

**Issue by Billy-** [babel/babel#8802]
# Possible Bug Report / Question

I know this has been covered in a few different places, but they all seem to use webpack or something else, and none of the solutions worked for me. I am just using babel - babel-cli to build and babel-node in conjunction with nodemon for development.

I have some namespaced node modules, which distribute their (untranspiled) source code. I want this folder to be transpiled, but nothing I have tried has worked. Notice below the `console.log` in the ignore function. This is never called with any files in node_modules.

Based on [this comment](https://github.com/babel/babel/issues/8309#issuecomment-405664954) I added `exclude: []` and `include: [/src/, /node_modules/]`, but neither made any difference.

###  Directory structure
```
/my-project
  /node_modules
  /src
    ...files
  package.json
  yarn.lock
  babel.config.js
```
### package.json
The relevant scripts/commands are `start-dev` and `babel`
```json
{
  "name": "firmware-service",
  "version": "1.0.0",
  "main": "index.js",
  "license": "Proprietary",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git@private-repo/firmware-service.git"
  },
  "scripts": {
    "start": "node dist/app.js",
    "start-dev": "nodemon src/app.js --exec \"babel-node\"",
    "dev": "docker-compose up --build",
    "unit-test": "docker-compose -p firmware-service-unit-tests -f docker-compose.unit-test.yml up --exit-code-from unit-tests --build",
    "integration-test": "docker-compose -p firmware-service-integ-tests -f docker-compose.integration-test.yml up --exit-code-from integration-tests --build",
    "test": "docker-compose -p firmware-service-tests -f docker-compose.test.yml up --exit-code-from tests --build",
    "babel": "babel src -d ./dist",
    "lint": "eslint ./src"
  },
  "dependencies": {
    "@my-namespace/auth": "^2.2.0",
    "@my-namespace/server-logger": "^3.1.1",
    "@my-namespace/utilities": "^1.4.1",
    "axios": "^0.18.0",
    "express": "^4.16.3",
    "helmet": "^3.12.1",
    "jsonwebtoken": "^8.2.2",
    "mongoose": "^5.1.3",
    "multer": "^1.3.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/node": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "expect": "^23.5.0",
    "mocha": "^5.2.0",
    "nodemon": "^1.17.5",
    "supertest": "^3.1.0"
  }
}
```
### babel.config.js
```js
const config = {
  'presets': [
    [
      '@babel/preset-env',
      {
        'targets': {
          'node': 'current',
        },
      },
    ],
  ],
  'retainLines': true,
  'plugins': [
    // 'lodash',
    // 'transform-runtime',
    // 'syntax-object-rest-spread',
  ],
  include: [/src/, /node_modules/],
  exclude: [],
  ignore: [filename => {
    console.log({ filename })
    if (!/\/node_modules\//.test(filename)) {
      return false // if not in node_modules, we want to compile it
    } else if (/\/node_modules\/@my-namespace\//.test(filename)) {
      // its our source code, so we want to compile it
      return false
    }
    // it's in node modules and NOT our source code
    return true
  }],
}

module.exports = config
```
## Error Message

```
[nodemon] starting `babel-node src/app.js`                 
{ filename: '/home/bmathews/projects/firmware-service/src/app.js' }                                                    
/home/bmathews/projects/firmware-service/node_modules/@my-namespace/server-logger/src/index.js:1                            
(function (exports, require, module, __filename, __dirname) { export { default, setTransports } from './logger'        
                                                              ^^^^^^                                                   

SyntaxError: Unexpected token export                       
```
## Environment
```
"@babel/cli": "^7.1.2",
"@babel/core": "^7.1.2",
"@babel/node": "^7.0.0",
"@babel/preset-env": "^7.1.0",
```
- Node v10.10.0 / npm v6.4.1 / yarn v1.9.4
- OS: `Ubuntu 18.04.1`
- Monorepo: `no`
- How you are using Babel: `cli`, `babel-node`

**Comment by Billy-** [comment]
@mlavina that function should return false if the filename is not in `node_modules` (false being don't ignore), then false again if it's in `node_modules` but also in my `@my-namespace` namespace. After that, it will return true as anything that doesn't match those two conditions must be some other `node_module`.

**Comment by nicolo-ribaudo** [comment]
Probably also 
```js
ignore: /node_modules\/(?!@my-namespace)/
```
would work. If you need windows support, replace `\/` with `[\/\\]`.

**Comment by Billy-** [comment]
@nicolo-ribaudo unfortunately that isn't making any difference for me :(

I think the issue is before the ignore as the ignore function is never called with a filename in `node_modules`, only files in `src`

**Comment by nicolo-ribaudo** [comment]
Oh it could be because `node_modules` are excluded by default in Babel 7. Could you try to use that RegExp instead of `[]` in `exclude`?

**Comment by Billy-** [comment]
> Oh it could be because `node_modules` are excluded by default in Babel 7

Yup, that's what I'm failing to override. Adding the RE in `exclude` also makes no difference. I figured an empty array should be enough to override the default.. But neither work.

**Comment by mathisGuerin** [comment]
@Billy- Does the ./babel-register.js solution worked for you ? I'm facing the same problem.

**Comment by Billy-** [comment]
@mathisGuerin Yes the babel-register solution (pretty much exactly what @loganfsmyth said above) works fine for me.

@loganfsmyth 
> I don't really view babel-node as something meant for serious use beyond executing random scripts here and there

I'm not really sure why you feel this way, but then again I don't feel strongly enough nor am I confident enough in my opinion to lean either way. The only real reason I would prefer to use `babel-node` is to omit the need for the (rather superfluous) `babel-register.js` file.

Anyway, thanks for the response, I can see that this is expected/understood behaviour, so I guess I'll close this issue for now.

**Comment by nateshmbhat** [comment]
I had this problem because of older babel version which I fixed using a stackoverflow answer  : 
Check this stackoverflow answer : https://stackoverflow.com/a/53927430/6665568

**Comment by Billy-** [comment]
@nateshmbhat that is unrelated - this issue is regarding transpiling files inside `node_modules` with `babel-node`.

@alolis given what @loganfsmyth has said, I don't think this is being considered an issue/unexpected behaviour, so will leave the issue closed - unless @loganfsmyth or someone else can confirm that this is in fact still an issue.

<details><summary>Here is what I have in my `babel-register.js`:</summary>
<p>

```js
const path = require('path')

function getBabelConfig () {
  // You could hardcode your config here, or get it from wherever. Mine is kept in a separate tooling package.
  // See below for the contents of this file
  const configPath = path.join(process.cwd(), 'node_modules/@my-namespace/tooling/configs/babel/babel.config.js')
  return require(configPath)
}

const config = getBabelConfig()

require('@babel/register')(config)
```
And here's that babel.config.js (note the `ignore` property):
```js
const config = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
  retainLines: true,
  plugins: [
    'lodash',
    '@babel/transform-runtime',
    '@babel/syntax-object-rest-spread',
  ],
  exclude: [],
  ignore: [filename => {
    // Put whatever logic you like here
    if (!/\/node_modules\//.test(filename)) {
      return false // if not in node_modules, we want to compile it
    } else if (/\/node_modules\/@my-namespace\//.test(filename)) {
      // its our source code, so we want to compile it
      return false
    }
    // it's in node modules and NOT our source code
    return true
  }],
}

module.exports = config
```
</p>
</details>

**Comment by saul-mtz** [comment]
The "issue" is that [`@babel/node` ignores `node_modules` by default](https://babeljs.io/docs/en/babel-node#options), there are many ways to workaround this, for instance I only need transpile [lodash-es](https://www.npmjs.com/package/lodash-es) so I have something like:

**babel.config.js**
```javascript
module.exports = function (api) {
  const presets = [
    ...
  ];

  return {
    ignore: [/node_modules\/(?!lodash-es)/],
    presets,
    ...
  };
};
```

running using babel-node
```zsh
# Ignores nothing explicitly
babel-node script.js -i "[]"
```
