### ISSUE TITLE
Incorrect `name` of `dynamic function` .

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [babel/babel#8952]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
`({ [`fn`]: () => { } }).fn.name;`, expected `fn`, got `undefined`.
![image](https://user-images.githubusercontent.com/12682063/47792482-1b04e900-dd57-11e8-95c0-83dd014c99f4.png)
![image](https://user-images.githubusercontent.com/12682063/47792675-7d5de980-dd57-11e8-8cac-b118297319f0.png)

**Input Code**
- REPL or Repo link if applicable:
[REPL](https://babeljs.io/en/repl.html#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwBA2g5AZgdlAugLjMAlGAvAPjOAXzAPQDp5S4BDAWwFMBuAKFEgAN42U1Nd9jiZCtXoMgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

```js
({ ['fn']: () => { } }).fn.name;
({ [`fn`]: () => { } }).fn.name;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
![image](https://user-images.githubusercontent.com/12682063/47791961-dd539080-dd55-11e8-9e75-0d73a151816d.png)

**Environment**
- Babel version(s): v6.26.0
just use the online REPL of bablejs.io.

**Possible Solution**
This could work if babel compile the code above to that:
``` javascript
'use strict';

function _defineProperty(obj, key, value) { if (value instanceof Function) { Object.defineProperty(value, 'name', { value: key }); };  if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

_defineProperty({}, 'fn', function () {}).fn.name;
_defineProperty({}, 'fn', function () {}).fn.name;
```

**Comment by nicolo-ribaudo** [comment]
This has been fixed in Babel 7: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwBA2g5AZgdlAugLjMAlGAvAPjOAXzAPQDp5S4BDAWwFMBuAKFEgAN42U1Nd9jiZCtXoMgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.1.2&envVersion=

```js
function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

_defineProperty({}, 'fn', function fn() {}).fn.name;
_defineProperty({}, "fn", function fn() {}).fn.name;
```

**Comment by zhengxiaoyao0716** [comment]
![image](https://user-images.githubusercontent.com/12682063/47974149-32d7c680-e0e3-11e8-8006-ac52c940b974.png)
![image](https://user-images.githubusercontent.com/12682063/47974154-39663e00-e0e3-11e8-8544-ca37e6a0deda.png)

I have tried it but still not work.
