### ISSUE TITLE
 ReferenceError regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by xuchenchenBoy** [babel/babel#9849]
I'm building an SSR template, and when I use @babebl/register and then execute webpack (config), the system reported an error.
I tried @babel/polyfill and @babel/plugin-transform-runtime, but none of them worked.

### Input code
`index.js:`
```
require("ignore-styles");
require("@babel/register")({
  ignore: [/\/(build|node_modules)\//],
  presets: ["@babel/preset-env", "@babel/preset-react"],
  plugins: ["@babel/plugin-syntax-dynamic-import", "dynamic-import-node"]
});
require("./server");
```

`server.js`
```
const config = require('../config/webpack.dev.config.js')
const webpack = require('webpack')
const express = require('express')
const webpackDevMiddleware = require('webpack-dev-middleware') 
const reactRouter = require('react-router')
const StaticRouter = reactRouter.reactRouter;
const app = express()
const complier = webpack(config)
const PORT = 8090
...
app.use(webpackDevMiddleware(complier, {
  publicPath: config.output.publicPath
}))

app.listen(PORT , function() {
  console.log(`SSR running on port ${PORT }`);
})
```

`webpack.dev.config.js`
```
const paths = require('./paths')
const webpack = require('webpack')
const htmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: ['webpack-hot-middleware/client?reload=true', paths.appIndexJs],
  output: {
    path: paths.clientBuild,
    filename: '[name].bundle.js',
    chunkFilename: '[name].bundle.js',
    publicPath: paths.publicPath
  },
  devtool: 'eval-source-map',
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: [
            ['@babel/preset-env', { 
              useBuiltIns: 'usage', 
              corejs: "2",  
              targets: {
                  browsers: ['last 2 versions', 'ie >= 9'],
              },
            }],
            '@babel/preset-react'
          ]
        }
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx']
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new htmlWebpackPlugin({
      template: './client/index.html',
      filename: 'index.html'
    })
  ]
}
```
### Error message
![image](https://user-images.githubusercontent.com/14016766/56009309-fc494c00-5d11-11e9-8445-94fa34d980d7.png)

### Environment
* Babel version(s): 7.4.3
* Node/npm version: [e.g. Node 10.15.3/npm 6.4.1]
* OS: window 10

### Rep
https://github.com/xuchenchenBoy/ssr （Please execute npm run dev:server and release notes in server.js）

**Comment by steve-taylor** [comment]
You have used at least one of these features and it's not supported in at least one of your `target`s (`['last 2 versions', 'ie >= 9']`):

* `async`;
* generators (`function*`); and/or
* `async` generators

As a result, `@babel/preset-env` decides to use `@babel/plugin-transform-regenerator`, which relies on `regeneratorRuntime` being available globally.

To fix this, simply use [`regenerator-runtime`](https://www.npmjs.com/package/regenerator-runtime), following the instructions in its README to ensure `regeneratorRuntime` is made available globally.

**Comment by lydell** [comment]
It feels like https://babeljs.io/docs/en/babel-preset-env could be improved, because currently it is unclear how to properly set up regenerator. Examples on different ways of doing would be great.

**Comment by PenguinTamer** [comment]
Any progress? I'm having the same issue

**Comment by nicolo-ribaudo** [comment]
@PenguinTamer Did you try using `useBuiltIns: usage`, `@babel/plugin-transform-runtime` or importing `regenerator-runtime`?

**Comment by PenguinTamer** [comment]
I did and resolved my issue, thank you for your answer though!

**Comment by matiasherranz** [comment]
> @PenguinTamer Did you try using `useBuiltIns: usage`, `@babel/plugin-transform-runtime` or importing `regenerator-runtime`?

This fixed my issue too. Thanks!

**Comment by yoyo837** [comment]
I'm use `@babel/plugin-transform-runtime`, still got this issue.

**Comment by sylvainDNS** [comment]
I had this issue using rollup with babel. I just used this babel config to resolve it : 
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          esmodules: true,
        },
      },
    ],
  ],
}
```

**Comment by humoyun** [comment]
@sylvainDNS it worked like a charm, thanks

**Comment by paddotk** [comment]
> I had this issue using rollup with babel. I just used this babel config to resolve it :
> 
> ```js
> module.exports = {
>   presets: [
>     [
>       '@babel/preset-env',
>       {
>         targets: {
>           esmodules: true,
>         },
>       },
>     ],
>   ],
> }
> ```

I can't get it to work, and Webpack doesn't seem to allow this snippet in any kind of way. I'm guessing most people use Webpack (and its config file isn't even preset if create-react-app is used) so what is the solution for the rest?

I installed `@babel/plugin-transform-runtime` within the app as well as `regenerator-runtime` globally, by the way.

**Comment by sylvainDNS** [comment]
This snippet must be put in `.babelrc.js` file (or just `.babelrc` if you use json).

If you use create-react-app, you must override webpack config with an external dependy as : 
- [craco](https://github.com/gsoft-inc/craco)
- [rescripts](https://github.com/harrysolovay/rescripts)
- [react-scripts-rewired](https://github.com/marcopeg/create-react-app/blob/master/packages/react-scripts/README.md)

**Comment by paddotk** [comment]
Ok, thanks, but... Is overriding Webpack config a clever thing to do? The point of packages such as create-react-app is to save a tremendous amount of hassle setting up a working Webpack configuration yourself. I've tried it before and spent over a day getting nowhere.

**Comment by sylvainDNS** [comment]
> "Stuff can break" — _Dan Abramov talking about [react-app-rewired](https://github.com/timarney/react-app-rewired) (deprecated for CRA > 2.0)_
> https://twitter.com/dan_abramov/status/1045809734069170176

This tweet is a troll, but you must keep in mind that if you override Webpack config in CRA, you own the config, and no support will be provided.  
However, overriding is a best alternative than ejecting your CRA.

Personally, I think that overriding webpack in CRA must be used with parsimony, and it isn't a bad thing if you know what you're doing. For instance, I'm mainly overriding CRA to use custom aliases.

But this subject is out of context :blush:

**Comment by nicolo-ribaudo** [comment]
CRA already includes `@babel/plugin-transform-runtime`: https://github.com/facebook/create-react-app/blob/3f699fd08044de9ab0ce1991a66b376d3e1956a8/packages/babel-preset-react-app/create.js#L162

**Comment by jackie1santana** [comment]
Easiest way to fix this 'regeneratorRuntime not defined issue' in your console:

You don't have to install any unnecessary plugins. Just add:

`<script src="https://unpkg.com/regenerator-runtime@0.13.1/runtime.js"></script>`

inside of the body in your index.html. Now regeneratorRuntime should be defined once you run babel and now your async/await functions should be compiled successfully into ES2015

**Comment by filipstoklasa** [comment]
this solution works for me:

```
 "plugins": [
    "@babel/plugin-transform-runtime",
....
  ]
```

**Comment by lderas** [comment]
> this solution works for me:
> 
> ```
>  "plugins": [
>     "@babel/plugin-transform-runtime",
> ....
>   ]
> ```

this one did it for me

**Comment by UkrainianCitizen** [comment]
> 
> 
> this solution works for me:
> 
> ```
>  "plugins": [
>     "@babel/plugin-transform-runtime",
> ....
>   ]
> ```

Where do you put this?

**Comment by yoyo837** [comment]
.bablerc

**Comment by UkrainianCitizen** [comment]
> 
> 
> .babelrc

Thanks, could you please elaborate, is this everything I supposedly need to do? Maybe I need to install `@babel/plugin-transform-runtime`, don't I?

**Comment by dairotenorio** [comment]
> > .babelrc
> 
> Thanks.
> This worked for me:
> 
> 1. `npm install --save-dev @babel/plugin-transform-runtime`
> 2. Including this in _.babelrc_
> 
> ```
> {
>     "plugins": [
>         "@babel/plugin-transform-runtime"
>     ]
> }
> ```

Thank you, this worked for me

**Comment by kheengz** [comment]
### Babel 7 Users

I had some trouble getting around this since most information was for prior babel versions. For Babel 7, install these two dependencies:

```
npm install --save @babel/runtime 
npm install --save-dev @babel/plugin-transform-runtime
```

And, in .babelrc, add:

```
{
    "presets": ["@babel/preset-env"],
    "plugins": [
        ["@babel/transform-runtime"]
    ]
}
```

**Comment by mhenriquesa** [comment]
> I had this issue using rollup with babel. I just used this babel config to resolve it :
> 
> ```js
> module.exports = {
>   presets: [
>     [
>       '@babel/preset-env',
>       {
>         targets: {
>           esmodules: true,
>         },
>       },
>     ],
>   ],
> }
> ```

Thankssss, Mate!! Like a charm

**Comment by ghostropic** [comment]
I had this issue but I knew it was working yesterday so I deleted node_modules and package.json lock file and it is working again without `@babel/plugin-transform-runtime`.  I think it should work as long as you're running `@babel/preset-env` and `core-js@3` with `useBuiltIns` set to `entry` or `usage`.
In `.babelrc` under presets:
```  
 [
  "@babel/preset-env",
    {
      "useBuiltIns": "entry",
      "corejs": "3"
    }
]
```
found here: https://babeljs.io/docs/en/babel-preset-env#usebuiltins

the key paragraph being as follows:

This option enables a new plugin that replaces the `import core-js/stable;` and `import "regenerator-runtime/runtime"` statements (or `require("core-js")` and `require("regenerator-runtime/runtime")`) with individual requires to different `core-js` entry points based on environment.

I'm not sure why it was broken when I woke up this morning and I hope I don't have to keep removing and reinstalling packages to get it to work.

**Comment by Arnaldo-Manjate** [comment]
> You have used at least one of these features and it's not supported in at least one of your `target`s (`['last 2 versions', 'ie >= 9']`):
> 
> * `async`;
> * generators (`function*`); and/or
> * `async` generators
> 
> As a result, `@babel/preset-env` decides to use `@babel/plugin-transform-regenerator`, which relies on `regeneratorRuntime` being available globally.
> 
> To fix this, simply use [`regenerator-runtime`](https://www.npmjs.com/package/regenerator-runtime), following the instructions in its README to ensure `regeneratorRuntime` is made available globally.

Where should the import of the runtime generator be put ?

**Comment by Arnaldo-Manjate** [comment]
What file should the import of the runtime generator be put ?

**Comment by ghostropic** [comment]
> What file should the import of the runtime generator be put ?

You could put it in your top level JS file to load everywhere, or individually in modules where it's needed, but you shouldn't have to manually import it if you're using Webpack and Babel which if set up correctly will inject it for you when needed. See my comment above.

**Comment by SharakPL** [comment]
```
npm i -D @babel/core @babel/preset-env core-js
```
No other plugins are needed.

### ["useBuiltIns": "entry"](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry):
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": 3,
        "debug": true
      }
    ]
  ]
}
```
then start your **main.js** with this:
```
import 'core-js';
import 'regenerator-runtime/runtime';
```
`regenerator-runtime/runtime` is @babel/preset-env dependencie.

The problem here is that it loads polyfills for all possible features that target browsers don't support natively. You can import just specific parts of core-js, but then you have to know exactly which part needs to be imported. That's why I prefer following config...

### ["useBuiltIns": "usage"](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage)
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": 3,
        "debug": true
      }
    ]
  ]
}
```
No extra imports are required. All pollyfills will be loaded automatically based on your code and Webpack will do the rest. 

----
As for the targets I think it's best to rely on browserslist in **package.json** instead of overriding it in .babelrc:
```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 edge version"
    ]
  },
```

**Comment by jacekkk** [comment]
> I had this issue using rollup with babel. I just used this babel config to resolve it :
> 
> ```js
> module.exports = {
>   presets: [
>     [
>       '@babel/preset-env',
>       {
>         targets: {
>           esmodules: true,
>         },
>       },
>     ],
>   ],
> }
> ```

Bear in mind that adding `esmodules: true` will lead to `browsers` target being ignored if you included it too, as per [Babel docs](https://babeljs.io/docs/en/babel-preset-env#targetsesmodules)

**Comment by Arnaldo-Manjate** [comment]
thanks its been resolved
*Arnaldo Manjate*
Developer

| T  011 680 0540
| E arnaldo@rapidtrade.com <shaun@rapidtrade.com>
| www.rapidtrade.com

**Comment by ayofish** [comment]
> > I had this issue using rollup with babel. I just used this babel config to resolve it :
> > ```js
> > module.exports = {
> >   presets: [
> >     [
> >       '@babel/preset-env',
> >       {
> >         targets: {
> >           esmodules: true,
> >         },
> >       },
> >     ],
> >   ],
> > }
> > ```
> 
> Thankssss, Mate!! Like a charm

This really saved me. Thank you!!

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "esmodules": true
        }
      }
    ]
  ]
}
```
 only things needed in .babelrc

**Comment by stla** [comment]
I had a similar problem but I don't use `.babelrc`. I solved by writing that in `webpack.config.js`:

```
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env',
                {
                  targets: {
                    esmodules: true
                  }
                }
              ],
              '@babel/preset-react'
            ]
          }
        }
      ]
    }
```

**Comment by EddieOne** [comment]
None of these are working for me.

**Comment by Arnaldo-Manjate** [comment]
> > What file should the import of the runtime generator be put ?
> 
> You could put it in your top level JS file to load everywhere, or individually in modules where it's needed, but you shouldn't have to manually import it if you're using Webpack and Babel which if set up correctly will inject it for you when needed. See my comment above.

thanks

**Comment by SharakPL** [comment]
@EddieOne this one works perfectly https://github.com/babel/babel/issues/9849#issuecomment-646245498
For development targets:

> Using targets:
> {
>   "chrome": "83",
>   "edge": "83",
>   "firefox": "77",
>   "safari": "13.1"
> }
> 
> Using modules transform: auto
> 
> Using plugins:
>   syntax-numeric-separator { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   proposal-logical-assignment-operators { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-nullish-coalescing-operator { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-optional-chaining { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-json-strings { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-optional-catch-binding { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-async-generators { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-object-rest-spread { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   transform-dotall-regex { "firefox":"77" }
>   proposal-unicode-property-regex { "firefox":"77" }
>   transform-named-capturing-groups-regex { "firefox":"77" }
>   proposal-export-namespace-from { "firefox":"77", "safari":"13.1" }
>   syntax-dynamic-import { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
>   syntax-top-level-await { "chrome":"83", "edge":"83", "firefox":"77", "safari":"13.1" }
> 
> Using polyfills with `usage` option:
> Based on your code and targets, core-js polyfills were not added.

**Only modern browsers targeted so no regenerator-runtime needed!**

For production targets:

> Using targets:
> 
> {
>   "chrome": "49",
>   "edge": "18",
>   "firefox": "68",
>   "ie": "11",
>   "ios": "12",
>   "opera": "68",
>   "safari": "12.1",
>   "samsung": "10.1"
> }
> 
> Using modules transform: auto
> 
> Using plugins:
>   proposal-numeric-separator { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "safari":"12.1", "samsung":"10.1" }
>   proposal-logical-assignment-operators { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "opera":"68", "safari":"12.1", "samsung":"10.1" }
>   proposal-nullish-coalescing-operator { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "safari":"12.1", "samsung":"10.1" }
>   proposal-optional-chaining { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "safari":"12.1", "samsung":"10.1" }
>   proposal-json-strings { "chrome":"49", "edge":"18", "ie":"11" }
>   proposal-optional-catch-binding { "chrome":"49", "edge":"18", "ie":"11" }
>   transform-parameters { "ie":"11" }
>   proposal-async-generator-functions { "chrome":"49", "edge":"18", "ie":"11" }
>   proposal-object-rest-spread { "chrome":"49", "edge":"18", "ie":"11" }
>   transform-dotall-regex { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11" }
>   proposal-unicode-property-regex { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11" }
>   transform-named-capturing-groups-regex { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11" }
>   transform-async-to-generator { "chrome":"49", "ie":"11" }
>   transform-exponentiation-operator { "chrome":"49", "ie":"11" }
>   transform-template-literals { "ie":"11", "ios":"12", "safari":"12.1" }
>   transform-literals { "ie":"11" }
>   transform-function-name { "chrome":"49", "edge":"18", "ie":"11" }
>   transform-arrow-functions { "ie":"11" }
>   transform-classes { "ie":"11" }
>   transform-object-super { "ie":"11" }
>   transform-shorthand-properties { "ie":"11" }
>   transform-duplicate-keys { "ie":"11" }
>   transform-computed-properties { "ie":"11" }
>   transform-for-of { "chrome":"49", "ie":"11" }
>   transform-sticky-regex { "ie":"11" }
>   transform-unicode-escapes { "ie":"11" }
>   transform-unicode-regex { "chrome":"49", "ie":"11" }
>   transform-spread { "ie":"11" }
>   transform-destructuring { "chrome":"49", "ie":"11" }
>   transform-block-scoping { "ie":"11" }
>   transform-typeof-symbol { "ie":"11" }
>   transform-new-target { "ie":"11" }
>   transform-regenerator { "chrome":"49", "ie":"11" }
>   proposal-export-namespace-from { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "safari":"12.1", "samsung":"10.1" }
>   syntax-dynamic-import { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "opera":"68", "safari":"12.1", "samsung":"10.1" }
>   syntax-top-level-await { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11", "ios":"12", "opera":"68", "safari":"12.1", "samsung":"10.1" }
> 
> Using polyfills with `usage` option:
> Added following core-js polyfills:
>   es.object.to-string { "ie":"11" }
>   es.promise { "chrome":"49", "edge":"18", "firefox":"68", "ie":"11" }
> 
> **Based on your code and targets, added regenerator-runtime.** 👈👈👈

**Comment by EddieOne** [comment]
I don't get it. It was working before. I tried several suggestions and the solution is not clear.
https://github.com/Y8Games/Y8-ai-gym/commit/f7243ea29521ddd2e3c865c5b9e684cdd253e4b1

**Comment by KonradLinkowski** [comment]
Do anybody know working alternative of babel? I'm tired of setting this up and fighting with hundreds of bugs. I just wanted to compile one file, but I babel is not capable of doing that.

**Comment by sylvainDNS** [comment]
I don't think it is the good place but maybe you can try swc https://github.com/swc-project/swc

**Comment by KonradLinkowski** [comment]
Nevermind I just fixed all my problems by adding polyfill for babel in my project which seems hilarious that library used to downgrade code needs polyfill.

**Comment by SharakPL** [comment]
> Do anybody know working alternative of babel? I'm tired of setting this up and fighting with hundreds of bugs. I just wanted to compile one file, but I babel is not capable of doing that.

Have you tried my solution above with "usage" option? It works perfectly for me. I have no idea why you all have such big problem to set this up. Show me your webpack config and maybe I'll be able to help.

**Comment by KonradLinkowski** [comment]
@SharakPL  I was using CLI  / online repl. Nothing worked without polyfill. I just wanted to make one file work on IE for one-time test.

**Comment by SharakPL** [comment]
I made my config specifically for IE11 and it works perfectly. Adds pollyfills automatically if needed.

**Comment by EddieOne** [comment]
Still not working for me. https://github.com/Y8Games/Y8-ai-gym/blob/master/webpack.config.js

**Comment by SharakPL** [comment]
@EddieOne this config is for new `@babel` packages and separate `core-js`. You're using old packages. Once again, refer to my first post here. Each config is linked to specific babel docs section and it shows exactly which packages need to be installed.

**Comment by makuzaverite** [comment]
> I had this issue using rollup with babel. I just used this babel config to resolve it :
> 
> ```js
> module.exports = {
>   presets: [
>     [
>       '@babel/preset-env',
>       {
>         targets: {
>           esmodules: true,
>         },
>       },
>     ],
>   ],
> }
> ```

This worked for me thanks
@sylvainDNS  

i have to write it like this though

in my ```.bablerc``` 

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "esmodules": true
        }
      }
    ],
    "@babel/preset-react"
  ]
}

```

**Comment by talmobi** [comment]
This thread is a sad testament into how blown to shit the situation is.

🙏🙏🙏 Here's a few prayers for future lost souls 🙏🙏🙏

**Comment by Denisiuk** [comment]
1. Install babel-polyfill
`npm install --save @babel/polyfill`

2. Update webpack file
`entry: ["@babel/polyfill", "<your enter js file>"]`

**Comment by nicolo-ribaudo** [comment]
Note that `@babel/polyfill` has been deprecated for a while. To solve the `regeneratorRuntime` problem, you can do this:



* Install regenerator-runtime
  `npm install --save regenerator-runtime`
* Update webpack file
  `entry: ["regenerator-runtime/runtime.js", "<your enter js file>"]`

**Comment by janeiro-dev** [comment]
`import 'regenerator-runtime/runtime'`

**Comment by dhruv-shipmnts** [comment]
> > .babelrc
> 
> Thanks.
> This worked for me:
> 
> 1. `npm install --save-dev @babel/plugin-transform-runtime`
> 2. Including this in _.babelrc_
> 
> ```
> {
>     "plugins": [
>         "@babel/plugin-transform-runtime"
>     ]
> }
> ```

for me
```
module.exports = {
  plugins: ["@babel/transform-runtime"],
  presets: [
    [
      "@babel/preset-env",
      {
        targets: {
          esmodules: true,
        },
      },
    ],
  ],
};

```

**Comment by jasurkurbanovinit** [comment]
> @PenguinTamer Did you try using `useBuiltIns: usage`, `@babel/plugin-transform-runtime` or importing `regenerator-runtime`?

used  this `@babel/plugin-transform-runtime`  solved for me as well

**Comment by AntonOfTheWoods** [comment]
> This thread is a sad testament into how blown to shit the situation is.
> 
> 🙏🙏🙏 Here's a few prayers for future lost souls 🙏🙏🙏

I particularly appreciate how moving code from one file to another suddenly means this is now necessary, where it wasn't before.

**Comment by victorkamoto** [comment]
Babel, used by Parcel, generates a polyfill, but to avoid this error you need to also load the regenerator-runtime runtime.

One solution: add to the top of your main JavaScript file:

import 'regenerator-runtime/runtime'
Parcel will include this package by default, increasing the size of 25KB.

The solution that is the most efficient  is adding the browserslist property to your package.json.

For example:

"browserslist": [
  "last 1 Chrome version"
]
For testing is good enough. To support multiple browsers:

"browserslist": [
  "last 3 and_chr versions",
  "last 3 chrome versions",
  "last 3 opera versions",
  "last 3 ios_saf versions",
  "last 3 safari versions"
]

You have to add a version that’s recent enough to support async/await, so Babel does not try to add a polyfill.

Check all the valid values here: https://github.com/browserslist/browserslist

**Comment by thernstig** [comment]
1. If I install `@babel/plugin-transform-runtime` (as a dev dependency) and `@babel/runtime` as a production dependency. Am I then expected to use `useBuiltIns: 'usage'` as well? I do not find this clear.

2. And how does the `@babel/plugin-transform-runtime` option `corejs` relate to the option `corejs` in `@babel/preset-env`? (and one wants you to specify minor verison but the other one does not mention it).

The confusedness is complete 😄

**Comment by SharakPL** [comment]
@thernstig have you tried this https://github.com/babel/babel/issues/9849#issuecomment-646245498 ?

**Comment by thernstig** [comment]
@SharakPL those instructions are incorrect in two places. 1) `"useBuiltIns": "entry"` does not load polyfills for all features, it actually removes those not needed according to the docs 2) It is recommended to use `.browserlistrc` (or other browserlist config options), since many other tools than just babel use those.

My question was not related to your answer. That answer just shows _how_ it can be used, but not if I am _expected_ to use `useBuiltIns`.

**Comment by SharakPL** [comment]
@thernstig 1) you're right about this one
2) I was referring specifically to "_...browserslist in package.json **instead of overriding it in .babelrc**_". Either way (_.browserslistrc_ file or _browserslist:_ in package.json) will be good, however I do prefer package.json just to [avoid another config file](https://github.com/browserslist/browserslist#packagejson). I've updated my answer to be more clear on that.

You're also right that this does not answer your question. Sorry about that 😳 You can always check it yourself by using `debug: true`:

**babel.config.js**
```js
const packageJson = require('./package.json');

module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'usage',
        corejs: packageJson.dependencies['core-js'],
        debug: true,
      },
    ],
  ],
};
```

**Comment by thernstig** [comment]
Yes, but I suppose I was hoping this should be clear from the docs. 

note: It is better you use `.browserlistrc` because other tools (such as stylelint) use it, see https://github.com/browserslist/browserslist#browserslist- That way you can check more of your code than just Javascript.

**Comment by SharakPL** [comment]
Stylelint itself doesn't care about browserslist. Why would it? It's just a linter/formatter. Stylelint plugins like Autoprefixer [check package.json for browserslist](https://github.com/postcss/autoprefixer#browsers)

**Comment by ogbeche77** [comment]
> "@babel/plugin-transform-runtime",

Its June 20201, and this solution still works

**Comment by zot** [comment]
> Note that `@babel/polyfill` has been deprecated for a while. To solve the `regeneratorRuntime` problem, you can do this:
> 
> * Install regenerator-runtime
>   `npm install --save regenerator-runtime`
> * Update webpack file
>   `entry: ["regenerator-runtime/runtime.js", "<your enter js file>"]`

We're using Babel 6 (for reasons) and this worked for us, thanks very much!!!

**Comment by mokimo** [comment]
`import 'regenerator-runtime/runtime'` in the root file and
`import 'regenerator-runtime/runtime'` in my jest.config.js helped

**Comment by yoyo837** [comment]
> `import 'regenerator-runtime/runtime'` in the root file and
> `import 'regenerator-runtime/runtime'` in my jest.config.js helped

This is not preferred

**Comment by Magnuti** [comment]
[This commit](https://github.com/clarocity/react-planner/commit/3fdd0c89542ceaf0572f7e79e7733ee19ed78bd5) fixed it for me.

.babelrc file:
```
"plugins": [
    "transform-runtime"
  ],
```

and by adding `"babel-plugin-transform-runtime": "^6.23.0"` to `package.json` dev dependecies.
